# fly.toml file generated for core-rs-albatross on 2021-09-04T17:30:34+02:00

app = "core-rs-albatross"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "core:latest"

[env]
  LISTEN_ADDRESSES = "/ip4/0.0.0.0/tcp/8443/ws"
  NIMIQ_LOG_LEVEL = "debug"
  NIMIQ_LOG_TIMESTAMPS = "true"
  NIMIQ_MIN_PEERS = "2"
  NIMIQ_VALIDATOR = "validator"
  RPC_ENABLED = "true"
  RUST_BACKTRACE = "1"
  VALIDATOR_KEY = "196ffdb1a8acc7cbd76a251aeac0600a1d68b3aba1eba823b5e4dc5dbdcdc730afa752c05ab4f6ef8518384ad514f403c5a088a22b17bf1bc14f8ff8decc2a512c0a200f68d7bdf5a319b30356fe8d1d75ef510aed7a8660968c216c328a0000"

[mounts]
  destination = "/data"
  source = "albatross_data"

[[services]]
  internal_port = 8443
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 10000
    soft_limit = 10000

  [[services.ports]]
    port = 8443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "30s"
    restart_limit = 5
    timeout = "2s"

[[services]]
  internal_port = 8648
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 10000
    soft_limit = 10000

  [[services.ports]]
    handlers = ["tls"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "30s"
    restart_limit = 5
    timeout = "2s"
