# fly.toml file generated for core-rs-albatross-seed-2 on 2021-09-05T21:54:57+02:00

app = "core-rs-albatross-seed-2"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "core:latest"

[env]
  LISTEN_ADDRESSES = "/ip4/0.0.0.0/tcp/8443/ws"
  NIMIQ_LOG_LEVEL = "debug"
  NIMIQ_LOG_TIMESTAMPS = "true"
  NIMIQ_MIN_PEERS = "2"
  NIMIQ_SEED_NODES = "/dns4/core-rs-albatross.fly.dev/tcp/8443/ws"
  NIMIQ_VALIDATOR = "validator"
  RPC_ENABLED = "false"
  RUST_BACKTRACE = "1"
  VALIDATOR_KEY = "bfbf1e23855190f03222bb2b19dc9d25843494d22bf8ccc1f7abfe6b3b185b3bf76537ee70e7ac5c7c6d7a0046e671bf610572e1cf89b407a7cd095ab9f0868da80003121a26d4d3be1e1abd10861f6c8601e94e0e448f4b86b7512764460100"

[mounts]
  destination = "/data"
  source = "albatross_data"

[[services]]
  internal_port = 8443
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 10000
    soft_limit = 10000

  [[services.ports]]
    port = 8443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "30s"
    restart_limit = 5
    timeout = "2s"
